### CRIAR SALARIO
POST http://localhost:8080/salarios
Content-Type: application/json

{
    "valorSalario": 1350.00,
    "periodo": "PRIMEIRA_QUINZENA"
}

### BUSCAR SALARIO(s)
GET http://localhost:8080/salarios

### ATUALIZAR SALARIO
PATCH http://localhost:8080/salarios/1
Content-Type: application/json

{
    "valorSalario": 2350.00,
    "periodo": "PRIMEIRA_QUINZENA"
}

// ------------------------------------ PESSOA ------------------------------------

### CRIAR PESSOA
POST http://localhost:8080/pessoas
Content-Type: application/json

{
  "nome": "Marcos Maia",
  "salarioIds": [4,5]

}

### BUSCAR PESSOAS
GET http://localhost:8080/pessoas


### CRIAR FAMILIA

POST http://localhost:8080/familias
Content-Type: application/json

{
  "nomeDaFamilia": "Familia-Silva",
  "membrosIds": [4,7]

}

### ADICIONAR MEMBROS

PATCH http://localhost:8080/familias/1
Content-Type: application/json

{
   "membrosIds": [4,6]
}

### CONTA AVULSA
POST http://localhost:8080/conta-avulsa
Content-Type: application/json

{
  "dataVencimento": "2024-11-25",
  "familiaId": 3,
  "despesa": {
    "descricao": "Conta de Gaz da Comgaz",
    "valor": 350.90,
    "periodo": "PRIMEIRA_QUINZENA"
  }
}