### CRIAR SALARIO
POST http://localhost:8080/salarios
Content-Type: application/json

{
    "valorSalario": 1000.00,
    "periodo": "SEGUNDA_QUINZENA"
}

### BUSCAR SALARIO(s)
GET http://localhost:8080/salarios

### CRIAR PESSOA
POST http://localhost:8080/pessoas
Content-Type: application/json

{
  "nome": "Daniel Brown",
  "salarioIds": [1, 2]

}