### CRIAR SALARIO
POST http://localhost:8080/salarios
Content-Type: application/json

{
    "valorSalario": 3500.00,
    "periodo": "SEGUNDA_QUINZENA"
}

### BUSCAR SALARIO(s)
GET http://localhost:8080/salarios

### ATUALIZAR SALARIO
PATCH http://localhost:8080/salarios/1
Content-Type: application/json

{
    "valorSalario": 1500.00,
    "periodo": "PRIMEIRA_QUINZENA"
}

// ------------------------------------ PESSOA ------------------------------------

### CRIAR PESSOA
POST http://localhost:8080/pessoas
Content-Type: application/json

{
  "nome": "Junior Silva",
  "salarioIds": [3]

}

### BUSCAR PESSOAS
GET http://localhost:8080/pessoas


### CRIAR FAMILIA

POST http://localhost:8080/familias
Content-Type: application/json

{
  "nomeDaFamilia": "Familia-Silva",
  "membrosIds": [1,4,6]

}
