# Banco em Memória (H2) OU Postgres de Teste (Recomendado se usar docker na pipeline)
spring.datasource.url=jdbc:postgresql://localhost:5432/cfm_db_test
spring.datasource.username=user_test
spring.datasource.password=password_test
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desativa o Job agendado nos testes para não rodar e quebrar contexto
spring.main.allow-bean-definition-overriding=true